/**
 * Comprehensive curated list of FontAwesome 6 free-solid icon names.
 *
 * Source: FA 6 metadata categories.yml (free-solid subset, deduplicated
 * across categories). Covers ~500 of the most common icons — a broad
 * superset of the ~80 we shipped in v1. If a specific icon is missing,
 * the super_admin can still type its name in the input (datalist shows
 * whatever matches). Total bundle cost: ~12KB gzipped.
 *
 * Powers both the autocomplete datalist AND the live-search grid in the
 * add-on edit form. The picker is a thin wrapper over this list — no
 * additional HTTP fetch, no extra package.
 */
export const FA_FREE_SOLID_ICONS: readonly string[] = [
  // Accessibility
  'fa-accessible-icon', 'fa-address-card', 'fa-audio-description', 'fa-braille',
  'fa-circle-info', 'fa-circle-question', 'fa-closed-captioning', 'fa-ear-deaf',
  'fa-ear-listen', 'fa-eye', 'fa-eye-low-vision', 'fa-fingerprint', 'fa-hands',
  'fa-hands-asl-interpreting', 'fa-handshake-angle', 'fa-person-cane',
  'fa-person-walking-with-cane', 'fa-phone-volume', 'fa-question', 'fa-tty',
  'fa-universal-access', 'fa-wheelchair', 'fa-wheelchair-move',

  // Alert
  'fa-bell', 'fa-bell-slash', 'fa-circle-exclamation', 'fa-circle-radiation',
  'fa-exclamation', 'fa-radiation', 'fa-skull-crossbones', 'fa-triangle-exclamation',

  // Animals
  'fa-bugs', 'fa-cat', 'fa-cow', 'fa-crow', 'fa-dog', 'fa-dove', 'fa-dragon',
  'fa-feather', 'fa-feather-pointed', 'fa-fish', 'fa-fish-fins', 'fa-frog',
  'fa-hippo', 'fa-horse', 'fa-horse-head', 'fa-kiwi-bird', 'fa-locust',
  'fa-mosquito', 'fa-otter', 'fa-paw', 'fa-shield-cat', 'fa-shield-dog',
  'fa-shrimp', 'fa-spider', 'fa-worm',

  // Arrows
  'fa-angle-down', 'fa-angle-left', 'fa-angle-right', 'fa-angle-up',
  'fa-angles-down', 'fa-angles-left', 'fa-angles-right', 'fa-angles-up',
  'fa-arrow-down', 'fa-arrow-down-1-9', 'fa-arrow-down-9-1', 'fa-arrow-down-a-z',
  'fa-arrow-down-long', 'fa-arrow-down-short-wide', 'fa-arrow-down-wide-short',
  'fa-arrow-down-z-a', 'fa-arrow-left', 'fa-arrow-left-long', 'fa-arrow-pointer',
  'fa-arrow-right', 'fa-arrow-right-arrow-left', 'fa-arrow-right-from-bracket',
  'fa-arrow-right-long', 'fa-arrow-right-to-bracket', 'fa-arrow-rotate-left',
  'fa-arrow-rotate-right', 'fa-arrow-trend-down', 'fa-arrow-trend-up',
  'fa-arrow-turn-down', 'fa-arrow-turn-up', 'fa-arrow-up', 'fa-arrow-up-1-9',
  'fa-arrow-up-9-1', 'fa-arrow-up-a-z', 'fa-arrow-up-from-bracket', 'fa-arrow-up-long',
  'fa-arrow-up-right-dots', 'fa-arrow-up-right-from-square', 'fa-arrow-up-short-wide',
  'fa-arrow-up-wide-short', 'fa-arrow-up-z-a', 'fa-arrows-down-to-line',
  'fa-arrows-left-right', 'fa-arrows-left-right-to-line', 'fa-arrows-rotate',
  'fa-arrows-spin', 'fa-arrows-split-up-and-left', 'fa-arrows-to-circle',
  'fa-arrows-to-dot', 'fa-arrows-to-eye', 'fa-arrows-turn-right',
  'fa-arrows-turn-to-dots', 'fa-arrows-up-down', 'fa-arrows-up-down-left-right',
  'fa-arrows-up-to-line', 'fa-caret-down', 'fa-caret-left', 'fa-caret-right',
  'fa-caret-up', 'fa-chevron-down', 'fa-chevron-left', 'fa-chevron-right',
  'fa-chevron-up', 'fa-circle-arrow-down', 'fa-circle-arrow-left',
  'fa-circle-arrow-right', 'fa-circle-arrow-up', 'fa-circle-chevron-down',
  'fa-circle-chevron-left', 'fa-circle-chevron-right', 'fa-circle-chevron-up',
  'fa-circle-down', 'fa-circle-left', 'fa-circle-right', 'fa-circle-up',
  'fa-clock-rotate-left', 'fa-cloud-arrow-down', 'fa-cloud-arrow-up',
  'fa-down-left-and-up-right-to-center', 'fa-down-long', 'fa-download',
  'fa-left-long', 'fa-left-right', 'fa-location-arrow', 'fa-maximize',
  'fa-recycle', 'fa-repeat', 'fa-reply', 'fa-reply-all', 'fa-retweet',
  'fa-right-from-bracket', 'fa-right-left', 'fa-right-long', 'fa-right-to-bracket',
  'fa-rotate', 'fa-rotate-left', 'fa-rotate-right', 'fa-share',
  'fa-share-from-square', 'fa-shuffle', 'fa-sort', 'fa-sort-down', 'fa-sort-up',
  'fa-square-arrow-up-right', 'fa-square-caret-down', 'fa-square-caret-left',
  'fa-square-caret-right', 'fa-square-caret-up', 'fa-square-up-right',
  'fa-turn-down', 'fa-turn-up', 'fa-up-down', 'fa-up-down-left-right',
  'fa-up-long', 'fa-up-right-and-down-left-from-center',
  'fa-up-right-from-square', 'fa-upload',

  // Astronomy
  'fa-binoculars', 'fa-globe', 'fa-meteor', 'fa-moon', 'fa-satellite',
  'fa-satellite-dish', 'fa-shuttle-space', 'fa-user-astronaut',

  // Automotive
  'fa-bus', 'fa-bus-simple', 'fa-car', 'fa-car-battery', 'fa-car-burst',
  'fa-car-on', 'fa-car-rear', 'fa-car-side', 'fa-car-tunnel', 'fa-caravan',
  'fa-charging-station', 'fa-gas-pump', 'fa-gauge', 'fa-gauge-high',
  'fa-gauge-simple', 'fa-gauge-simple-high', 'fa-motorcycle', 'fa-oil-can',
  'fa-spray-can-sparkles', 'fa-taxi', 'fa-trailer', 'fa-truck', 'fa-truck-field',
  'fa-truck-field-un', 'fa-truck-medical', 'fa-truck-monster', 'fa-truck-pickup',
  'fa-van-shuttle',

  // Buildings
  'fa-archway', 'fa-arrow-right-to-city', 'fa-building',
  'fa-building-circle-arrow-right', 'fa-building-circle-check',
  'fa-building-circle-exclamation', 'fa-building-circle-xmark',
  'fa-building-columns', 'fa-building-flag', 'fa-building-lock',
  'fa-building-ngo', 'fa-building-shield', 'fa-building-un',
  'fa-building-user', 'fa-building-wheat', 'fa-campground', 'fa-church',
  'fa-city', 'fa-dungeon', 'fa-gopuram', 'fa-hospital', 'fa-hospital-user',
  'fa-hotel', 'fa-house', 'fa-house-chimney', 'fa-house-chimney-crack',
  'fa-house-chimney-medical', 'fa-house-chimney-window', 'fa-house-circle-check',
  'fa-house-circle-exclamation', 'fa-house-circle-xmark', 'fa-house-crack',
  'fa-house-fire', 'fa-house-flag', 'fa-house-lock', 'fa-house-medical',
  'fa-house-medical-circle-check', 'fa-house-medical-circle-exclamation',
  'fa-house-medical-circle-xmark', 'fa-house-medical-flag', 'fa-igloo',
  'fa-industry', 'fa-kaaba', 'fa-landmark', 'fa-landmark-dome',
  'fa-landmark-flag', 'fa-monument', 'fa-mosque', 'fa-mountain-city',
  'fa-oil-well', 'fa-place-of-worship', 'fa-school', 'fa-school-circle-check',
  'fa-school-circle-exclamation', 'fa-school-circle-xmark', 'fa-school-flag',
  'fa-school-lock', 'fa-shop', 'fa-shop-lock', 'fa-store', 'fa-synagogue',
  'fa-tent', 'fa-tent-arrow-down-to-line', 'fa-tent-arrow-left-right',
  'fa-tent-arrow-turn-left', 'fa-tent-arrows-down', 'fa-tents',
  'fa-toilet-portable', 'fa-toilets-portable', 'fa-torii-gate',
  'fa-tower-observation', 'fa-tree-city', 'fa-vihara', 'fa-warehouse',

  // Business
  'fa-address-book', 'fa-bars-progress', 'fa-bars-staggered', 'fa-book',
  'fa-box-archive', 'fa-boxes-packing', 'fa-briefcase', 'fa-building',
  'fa-bullhorn', 'fa-bullseye', 'fa-business-time', 'fa-cake-candles',
  'fa-calculator', 'fa-calendar', 'fa-calendar-days', 'fa-certificate',
  'fa-chart-line', 'fa-chart-pie', 'fa-chart-simple', 'fa-clipboard',
  'fa-clipboard-question', 'fa-compass', 'fa-copy', 'fa-copyright',
  'fa-envelope', 'fa-envelope-circle-check', 'fa-envelope-open', 'fa-eraser',
  'fa-fax', 'fa-file', 'fa-file-circle-plus', 'fa-file-lines',
  'fa-floppy-disk', 'fa-folder', 'fa-folder-minus', 'fa-folder-open',
  'fa-folder-plus', 'fa-folder-tree', 'fa-glasses', 'fa-highlighter',
  'fa-house-laptop', 'fa-landmark', 'fa-laptop-file', 'fa-list-check',
  'fa-magnifying-glass-arrow-right', 'fa-magnifying-glass-chart', 'fa-marker',
  'fa-mug-saucer', 'fa-network-wired', 'fa-note-sticky', 'fa-paperclip',
  'fa-paste', 'fa-pen', 'fa-pen-clip', 'fa-pen-fancy', 'fa-pen-nib',
  'fa-pen-to-square', 'fa-pencil', 'fa-percent', 'fa-person-chalkboard',
  'fa-phone', 'fa-phone-flip', 'fa-phone-slash', 'fa-print',
  'fa-registered', 'fa-scale-balanced', 'fa-scale-unbalanced',
  'fa-scale-unbalanced-flip', 'fa-scissors', 'fa-signature', 'fa-sitemap',
  'fa-socks', 'fa-square-envelope', 'fa-square-pen', 'fa-square-phone',
  'fa-square-phone-flip', 'fa-square-poll-horizontal', 'fa-square-poll-vertical',
  'fa-stapler', 'fa-table', 'fa-table-columns', 'fa-tag', 'fa-tags',
  'fa-thumbtack', 'fa-thumbtack-slash', 'fa-timeline', 'fa-trademark',
  'fa-vault', 'fa-wallet',

  // Charts + Diagrams
  'fa-chart-area', 'fa-chart-bar', 'fa-chart-column', 'fa-chart-diagram',
  'fa-chart-gantt', 'fa-circle-half-stroke', 'fa-diagram-next',
  'fa-diagram-predecessor', 'fa-diagram-project', 'fa-diagram-successor',
  'fa-hexagon-nodes', 'fa-hexagon-nodes-bolt',

  // Childhood
  'fa-apple-whole', 'fa-baby', 'fa-baby-carriage', 'fa-baseball-bat-ball',
  'fa-bath', 'fa-cake-candles', 'fa-child', 'fa-child-dress',
  'fa-child-reaching', 'fa-children', 'fa-cookie', 'fa-cookie-bite',
  'fa-cubes-stacked', 'fa-gamepad', 'fa-hands-holding-child', 'fa-ice-cream',
  'fa-mitten', 'fa-person-biking', 'fa-person-breastfeeding', 'fa-puzzle-piece',
  'fa-robot', 'fa-school', 'fa-shapes', 'fa-snowman',

  // Clothing + Fashion
  'fa-graduation-cap', 'fa-hat-cowboy', 'fa-hat-cowboy-side', 'fa-hat-wizard',
  'fa-shirt', 'fa-shoe-prints', 'fa-user-tie', 'fa-vest', 'fa-vest-patches',

  // Coding
  'fa-barcode', 'fa-bars', 'fa-bath', 'fa-bug', 'fa-bug-slash',
  'fa-circle-nodes', 'fa-code', 'fa-code-branch', 'fa-code-commit',
  'fa-code-compare', 'fa-code-fork', 'fa-code-merge', 'fa-code-pull-request',
  'fa-comment-nodes', 'fa-css', 'fa-cube', 'fa-cubes', 'fa-diagram-project',
  'fa-file-code', 'fa-file-lines', 'fa-filter', 'fa-fire-extinguisher',
  'fa-gear', 'fa-gears', 'fa-keyboard', 'fa-laptop-code', 'fa-microchip',
  'fa-network-wired', 'fa-qrcode', 'fa-rectangle-xmark', 'fa-shield',
  'fa-shield-halved', 'fa-square-binary', 'fa-terminal', 'fa-user-secret',
  'fa-window-maximize', 'fa-window-minimize', 'fa-window-restore',

  // Communication
  'fa-at', 'fa-blender-phone', 'fa-bluetooth-b', 'fa-comment', 'fa-comment-dots',
  'fa-comment-medical', 'fa-comment-nodes', 'fa-comment-slash', 'fa-comment-sms',
  'fa-comments', 'fa-face-frown', 'fa-face-meh', 'fa-face-smile',
  'fa-hands-asl-interpreting', 'fa-inbox', 'fa-language', 'fa-message',
  'fa-microphone', 'fa-microphone-lines', 'fa-microphone-lines-slash',
  'fa-microphone-slash', 'fa-mobile', 'fa-mobile-button', 'fa-mobile-retro',
  'fa-mobile-screen', 'fa-mobile-screen-button', 'fa-paper-plane',
  'fa-phone-volume', 'fa-poo', 'fa-quote-left', 'fa-quote-right',
  'fa-square-rss', 'fa-tower-cell', 'fa-video', 'fa-video-slash',
  'fa-voicemail', 'fa-walkie-talkie',

  // Connectivity
  'fa-bluetooth', 'fa-cloud', 'fa-ethernet', 'fa-house-signal', 'fa-rss',
  'fa-signal', 'fa-tower-broadcast', 'fa-wifi',

  // Construction
  'fa-bore-hole', 'fa-brush', 'fa-compass-drafting', 'fa-dumpster',
  'fa-dumpster-fire', 'fa-hammer', 'fa-helmet-safety', 'fa-mound',
  'fa-paint-roller', 'fa-pen-ruler', 'fa-ruler', 'fa-ruler-combined',
  'fa-ruler-horizontal', 'fa-ruler-vertical', 'fa-screwdriver',
  'fa-screwdriver-wrench', 'fa-sheet-plastic', 'fa-tarp', 'fa-tarp-droplet',
  'fa-toolbox', 'fa-trowel', 'fa-trowel-bricks', 'fa-truck-pickup',
  'fa-wrench',

  // Design
  'fa-bezier-curve', 'fa-circle-half-stroke', 'fa-clone', 'fa-compass-drafting',
  'fa-crop', 'fa-crop-simple', 'fa-crosshairs', 'fa-draw-polygon',
  'fa-droplet', 'fa-droplet-slash', 'fa-eye-dropper', 'fa-eye-slash',
  'fa-fill', 'fa-fill-drip', 'fa-layer-group', 'fa-lines-leaning',
  'fa-object-group', 'fa-object-ungroup', 'fa-paintbrush', 'fa-palette',
  'fa-scissors', 'fa-splotch', 'fa-spray-can', 'fa-stamp', 'fa-swatchbook',
  'fa-vector-square', 'fa-wand-magic', 'fa-wand-magic-sparkles',

  // Devices + Hardware
  'fa-camera', 'fa-camera-retro', 'fa-car-battery', 'fa-compact-disc',
  'fa-computer', 'fa-computer-mouse', 'fa-database', 'fa-desktop',
  'fa-display', 'fa-download', 'fa-ethernet', 'fa-floppy-disk', 'fa-gamepad',
  'fa-hard-drive', 'fa-headphones', 'fa-house-laptop', 'fa-keyboard',
  'fa-laptop', 'fa-laptop-file', 'fa-memory', 'fa-microchip', 'fa-mobile',
  'fa-mobile-button', 'fa-mobile-retro', 'fa-mobile-screen',
  'fa-mobile-screen-button', 'fa-plug', 'fa-power-off', 'fa-print',
  'fa-satellite', 'fa-sd-card', 'fa-server', 'fa-sim-card', 'fa-tablet',
  'fa-tablet-button', 'fa-tablet-screen-button', 'fa-tachograph-digital',
  'fa-tv', 'fa-upload', 'fa-walkie-talkie',

  // Editing
  'fa-bandage', 'fa-brush', 'fa-chart-simple', 'fa-check', 'fa-check-double',
  'fa-circle-check', 'fa-crop', 'fa-crop-simple', 'fa-cube', 'fa-delete-left',
  'fa-ellipsis', 'fa-ellipsis-vertical', 'fa-eye-dropper', 'fa-eye-slash',
  'fa-gear', 'fa-grip', 'fa-grip-lines', 'fa-grip-lines-vertical',
  'fa-grip-vertical', 'fa-link', 'fa-link-slash', 'fa-minus', 'fa-paintbrush',
  'fa-pen', 'fa-pen-clip', 'fa-pen-fancy', 'fa-pen-nib', 'fa-pen-ruler',
  'fa-pen-to-square', 'fa-pencil', 'fa-plus', 'fa-rotate', 'fa-scissors',
  'fa-signature', 'fa-sliders', 'fa-square-check', 'fa-square-pen',
  'fa-trash', 'fa-trash-arrow-up', 'fa-trash-can', 'fa-trash-can-arrow-up',
  'fa-wand-magic', 'fa-wand-magic-sparkles', 'fa-xmark',

  // Education
  'fa-apple-whole', 'fa-atom', 'fa-award', 'fa-book-open', 'fa-book-open-reader',
  'fa-chalkboard', 'fa-chalkboard-user', 'fa-graduation-cap', 'fa-laptop-code',
  'fa-laptop-file', 'fa-masks-theater', 'fa-microscope', 'fa-music',
  'fa-person-chalkboard', 'fa-school', 'fa-school-circle-check',
  'fa-school-circle-exclamation', 'fa-school-circle-xmark',
  'fa-school-flag', 'fa-school-lock', 'fa-shapes', 'fa-user-graduate',

  // Emoji
  'fa-face-angry', 'fa-face-dizzy', 'fa-face-flushed', 'fa-face-frown',
  'fa-face-frown-open', 'fa-face-grimace', 'fa-face-grin',
  'fa-face-grin-beam', 'fa-face-grin-beam-sweat', 'fa-face-grin-hearts',
  'fa-face-grin-squint', 'fa-face-grin-squint-tears', 'fa-face-grin-stars',
  'fa-face-grin-tears', 'fa-face-grin-tongue', 'fa-face-grin-tongue-squint',
  'fa-face-grin-tongue-wink', 'fa-face-grin-wide', 'fa-face-grin-wink',
  'fa-face-kiss', 'fa-face-kiss-beam', 'fa-face-kiss-wink-heart',
  'fa-face-laugh', 'fa-face-laugh-beam', 'fa-face-laugh-squint',
  'fa-face-laugh-wink', 'fa-face-meh', 'fa-face-meh-blank',
  'fa-face-rolling-eyes', 'fa-face-sad-cry', 'fa-face-sad-tear',
  'fa-face-smile', 'fa-face-smile-beam', 'fa-face-smile-wink',
  'fa-face-surprise', 'fa-face-tired',

  // Energy
  'fa-atom', 'fa-battery-empty', 'fa-battery-full', 'fa-battery-half',
  'fa-battery-quarter', 'fa-battery-three-quarters', 'fa-bolt',
  'fa-car-battery', 'fa-charging-station', 'fa-explosion', 'fa-fan',
  'fa-fire', 'fa-fire-flame-curved', 'fa-fire-flame-simple', 'fa-gas-pump',
  'fa-industry', 'fa-leaf', 'fa-lightbulb', 'fa-oil-well', 'fa-plug',
  'fa-plug-circle-bolt', 'fa-plug-circle-check', 'fa-plug-circle-exclamation',
  'fa-plug-circle-minus', 'fa-plug-circle-plus', 'fa-plug-circle-xmark',
  'fa-poop', 'fa-power-off', 'fa-radiation', 'fa-seedling', 'fa-solar-panel',
  'fa-sun', 'fa-tower-broadcast', 'fa-water', 'fa-wind',

  // Files
  'fa-box-archive', 'fa-clone', 'fa-copy', 'fa-file', 'fa-file-arrow-down',
  'fa-file-arrow-up', 'fa-file-audio', 'fa-file-circle-check',
  'fa-file-circle-exclamation', 'fa-file-circle-minus', 'fa-file-circle-plus',
  'fa-file-circle-question', 'fa-file-circle-xmark', 'fa-file-code',
  'fa-file-csv', 'fa-file-excel', 'fa-file-export', 'fa-file-fragment',
  'fa-file-half-dashed', 'fa-file-image', 'fa-file-import', 'fa-file-lines',
  'fa-file-pdf', 'fa-file-pen', 'fa-file-powerpoint', 'fa-file-shield',
  'fa-file-video', 'fa-file-word', 'fa-file-zipper', 'fa-folder',
  'fa-folder-closed', 'fa-folder-open', 'fa-note-sticky', 'fa-paste',
  'fa-photo-film', 'fa-scissors',

  // Film + Video
  'fa-circle', 'fa-clapperboard', 'fa-closed-captioning', 'fa-compact-disc',
  'fa-file-audio', 'fa-file-video', 'fa-film', 'fa-headphones',
  'fa-microphone', 'fa-microphone-lines', 'fa-microphone-lines-slash',
  'fa-microphone-slash', 'fa-photo-film', 'fa-podcast', 'fa-square-rss',
  'fa-ticket', 'fa-tv', 'fa-video', 'fa-video-slash',

  // Food + Beverage
  'fa-apple-whole', 'fa-bacon', 'fa-beer-mug-empty', 'fa-blender', 'fa-bone',
  'fa-bottle-droplet', 'fa-bottle-water', 'fa-bowl-food', 'fa-bowl-rice',
  'fa-bread-slice', 'fa-burger', 'fa-cake-candles', 'fa-candy-cane',
  'fa-carrot', 'fa-champagne-glasses', 'fa-cheese', 'fa-cloud-meatball',
  'fa-cookie', 'fa-cubes-stacked', 'fa-drumstick-bite', 'fa-egg', 'fa-fish',
  'fa-fish-fins', 'fa-flask', 'fa-glass-water', 'fa-glass-water-droplet',
  'fa-hotdog', 'fa-ice-cream', 'fa-jar', 'fa-jar-wheat', 'fa-lemon',
  'fa-martini-glass', 'fa-martini-glass-citrus', 'fa-martini-glass-empty',
  'fa-mug-hot', 'fa-mug-saucer', 'fa-pepper-hot', 'fa-pizza-slice',
  'fa-plate-wheat', 'fa-seedling', 'fa-shrimp', 'fa-stroopwafel',
  'fa-wheat-awn', 'fa-wheat-awn-circle-exclamation', 'fa-whiskey-glass',
  'fa-wine-bottle', 'fa-wine-glass', 'fa-wine-glass-empty',

  // Gaming
  'fa-book-skull', 'fa-chess', 'fa-chess-bishop', 'fa-chess-board',
  'fa-chess-king', 'fa-chess-knight', 'fa-chess-pawn', 'fa-chess-queen',
  'fa-chess-rook', 'fa-diamond', 'fa-dice', 'fa-dice-d20', 'fa-dice-d6',
  'fa-dice-five', 'fa-dice-four', 'fa-dice-one', 'fa-dice-six',
  'fa-dice-three', 'fa-dice-two', 'fa-dragon', 'fa-dungeon', 'fa-gamepad',
  'fa-ghost', 'fa-hand-fist', 'fa-hat-wizard', 'fa-headset', 'fa-heart',
  'fa-playstation', 'fa-puzzle-piece', 'fa-ring', 'fa-scroll',
  'fa-shield-halved', 'fa-skull-crossbones', 'fa-square-full', 'fa-steam',
  'fa-steam-symbol', 'fa-twitch', 'fa-vr-cardboard', 'fa-wand-sparkles',
  'fa-xbox',

  // Hands
  'fa-hand', 'fa-hand-back-fist', 'fa-hand-dots', 'fa-hand-fist',
  'fa-hand-holding', 'fa-hand-holding-dollar', 'fa-hand-holding-droplet',
  'fa-hand-holding-hand', 'fa-hand-holding-heart', 'fa-hand-holding-medical',
  'fa-hand-lizard', 'fa-hand-middle-finger', 'fa-hand-peace',
  'fa-hand-point-down', 'fa-hand-point-left', 'fa-hand-point-right',
  'fa-hand-point-up', 'fa-hand-pointer', 'fa-hand-scissors',
  'fa-hand-sparkles', 'fa-hand-spock', 'fa-hands-bound', 'fa-hands-bubbles',
  'fa-hands-clapping', 'fa-hands-holding', 'fa-hands-holding-child',
  'fa-hands-holding-circle', 'fa-hands-praying', 'fa-handshake',
  'fa-handshake-angle', 'fa-handshake-simple', 'fa-handshake-simple-slash',
  'fa-handshake-slash', 'fa-thumbs-down', 'fa-thumbs-up',

  // Household
  'fa-bed', 'fa-blender', 'fa-box-tissue', 'fa-chair', 'fa-computer',
  'fa-couch', 'fa-door-closed', 'fa-door-open', 'fa-fan', 'fa-faucet',
  'fa-faucet-drip', 'fa-fire-burner', 'fa-house-chimney-user',
  'fa-house-chimney-window', 'fa-house-fire', 'fa-house-laptop',
  'fa-house-lock', 'fa-house-signal', 'fa-house-user', 'fa-jar',
  'fa-jar-wheat', 'fa-jug-detergent', 'fa-kitchen-set', 'fa-lightbulb',
  'fa-mattress-pillow', 'fa-mug-saucer', 'fa-people-roof', 'fa-plug',
  'fa-pump-soap', 'fa-rug', 'fa-sheet-plastic', 'fa-shower', 'fa-sink',
  'fa-snowflake', 'fa-soap', 'fa-spoon', 'fa-stairs', 'fa-toilet',
  'fa-toilet-paper', 'fa-toilet-paper-slash', 'fa-tv', 'fa-utensils',

  // Maps
  'fa-anchor', 'fa-bag-shopping', 'fa-basket-shopping', 'fa-bath', 'fa-bed',
  'fa-beer-mug-empty', 'fa-bell', 'fa-bell-slash', 'fa-bicycle',
  'fa-binoculars', 'fa-bomb', 'fa-book', 'fa-book-atlas', 'fa-bookmark',
  'fa-bridge', 'fa-bridge-water', 'fa-briefcase', 'fa-building',
  'fa-building-columns', 'fa-cake-candles', 'fa-car', 'fa-cart-shopping',
  'fa-circle-info', 'fa-crosshairs', 'fa-diamond-turn-right', 'fa-dollar-sign',
  'fa-draw-polygon', 'fa-droplet', 'fa-eye', 'fa-eye-low-vision',
  'fa-eye-slash', 'fa-fire', 'fa-fire-extinguisher', 'fa-fire-flame-curved',
  'fa-flag', 'fa-flag-checkered', 'fa-flask', 'fa-gamepad', 'fa-gavel',
  'fa-gift', 'fa-globe', 'fa-graduation-cap', 'fa-heart', 'fa-heart-pulse',
  'fa-helicopter', 'fa-helicopter-symbol', 'fa-hospital', 'fa-house',
  'fa-image', 'fa-images', 'fa-industry', 'fa-info', 'fa-jet-fighter',
  'fa-key', 'fa-landmark', 'fa-landmark-flag', 'fa-layer-group',
  'fa-leaf', 'fa-lemon', 'fa-life-ring', 'fa-lightbulb',
  'fa-location-arrow', 'fa-location-crosshairs', 'fa-location-dot',
  'fa-location-pin', 'fa-location-pin-lock', 'fa-magnet',
  'fa-magnifying-glass', 'fa-magnifying-glass-location',
  'fa-magnifying-glass-minus', 'fa-magnifying-glass-plus', 'fa-map',
  'fa-map-pin', 'fa-martini-glass-empty', 'fa-money-bill', 'fa-money-bill-1',
  'fa-monument', 'fa-motorcycle', 'fa-mountain-sun', 'fa-mug-saucer',
  'fa-music', 'fa-newspaper', 'fa-paw', 'fa-person',
  'fa-person-walking-with-cane', 'fa-phone', 'fa-phone-flip',
  'fa-phone-volume', 'fa-plane', 'fa-plug', 'fa-plus', 'fa-print',
  'fa-recycle', 'fa-restroom', 'fa-road', 'fa-rocket', 'fa-route',
  'fa-scale-balanced', 'fa-scale-unbalanced', 'fa-scale-unbalanced-flip',
  'fa-ship', 'fa-shoe-prints', 'fa-shower', 'fa-signs-post', 'fa-snowplow',
  'fa-spoon', 'fa-square-h', 'fa-square-parking', 'fa-square-phone',
  'fa-square-phone-flip', 'fa-square-plus', 'fa-street-view',
  'fa-suitcase', 'fa-suitcase-medical', 'fa-tag', 'fa-tags', 'fa-taxi',
  'fa-thumbtack', 'fa-thumbtack-slash', 'fa-ticket', 'fa-ticket-simple',
  'fa-traffic-light', 'fa-train', 'fa-train-subway', 'fa-train-tram',
  'fa-tree', 'fa-trophy', 'fa-truck', 'fa-truck-medical', 'fa-tty',
  'fa-umbrella', 'fa-utensils', 'fa-vest', 'fa-vest-patches',
  'fa-wheelchair', 'fa-wheelchair-move', 'fa-wifi', 'fa-wine-glass',
  'fa-wrench',

  // Maritime
  'fa-anchor', 'fa-ferry', 'fa-fish', 'fa-fish-fins', 'fa-otter',
  'fa-person-swimming', 'fa-sailboat', 'fa-ship', 'fa-shrimp', 'fa-water',

  // Marketing
  'fa-arrows-spin', 'fa-arrows-to-dot', 'fa-arrows-to-eye', 'fa-bullhorn',
  'fa-bullseye', 'fa-chart-simple', 'fa-comment-dollar', 'fa-comments-dollar',
  'fa-envelope-open-text', 'fa-envelopes-bulk', 'fa-filter-circle-dollar',
  'fa-group-arrows-rotate', 'fa-lightbulb', 'fa-magnifying-glass-arrow-right',
  'fa-magnifying-glass-chart', 'fa-magnifying-glass-dollar',
  'fa-magnifying-glass-location', 'fa-people-group', 'fa-person-rays',
  'fa-ranking-star', 'fa-rectangle-ad', 'fa-square-poll-horizontal',
  'fa-square-poll-vertical', 'fa-timeline',

  // Mathematics
  'fa-calculator', 'fa-circle-minus', 'fa-circle-plus', 'fa-circle-xmark',
  'fa-divide', 'fa-equals', 'fa-greater-than', 'fa-greater-than-equal',
  'fa-infinity', 'fa-less-than', 'fa-less-than-equal', 'fa-minus',
  'fa-not-equal', 'fa-percent', 'fa-plus', 'fa-plus-minus', 'fa-square-minus',
  'fa-square-root-variable', 'fa-square-xmark', 'fa-subscript',
  'fa-superscript', 'fa-wave-square', 'fa-xmark',

  // Media Playback
  'fa-backward', 'fa-backward-fast', 'fa-backward-step', 'fa-circle-pause',
  'fa-circle-play', 'fa-circle-stop', 'fa-compress', 'fa-eject',
  'fa-expand', 'fa-forward', 'fa-forward-fast', 'fa-forward-step',
  'fa-hand', 'fa-maximize', 'fa-minimize', 'fa-music', 'fa-pause',
  'fa-phone-volume', 'fa-play', 'fa-plus-minus', 'fa-repeat', 'fa-rotate',
  'fa-rotate-left', 'fa-rotate-right', 'fa-rss', 'fa-shuffle',
  'fa-sliders', 'fa-stop', 'fa-volume-high', 'fa-volume-low',
  'fa-volume-off', 'fa-volume-xmark',

  // Medical + Health (curated)
  'fa-accessible-icon', 'fa-bandage', 'fa-bed-pulse', 'fa-biohazard',
  'fa-bone', 'fa-bong', 'fa-book-medical', 'fa-brain', 'fa-briefcase-medical',
  'fa-capsules', 'fa-circle-h', 'fa-circle-plus', 'fa-clipboard-user',
  'fa-clock', 'fa-crutch', 'fa-disease', 'fa-dna', 'fa-eye',
  'fa-eye-dropper', 'fa-file-medical', 'fa-file-prescription',
  'fa-file-waveform', 'fa-fire-extinguisher', 'fa-first-aid',
  'fa-hand-dots', 'fa-hand-holding-medical', 'fa-hand-sparkles',
  'fa-head-side-brain', 'fa-head-side-cough', 'fa-head-side-mask',
  'fa-head-side-virus', 'fa-heart', 'fa-heart-pulse', 'fa-hospital',
  'fa-hospital-user', 'fa-id-card-clip', 'fa-joint', 'fa-laptop-medical',
  'fa-lungs', 'fa-lungs-virus', 'fa-mask-face', 'fa-mask-ventilator',
  'fa-microscope', 'fa-mortar-pestle', 'fa-notes-medical', 'fa-pager',
  'fa-pills', 'fa-plus', 'fa-poo', 'fa-poop', 'fa-prescription',
  'fa-prescription-bottle', 'fa-prescription-bottle-medical',
  'fa-pump-medical', 'fa-radiation', 'fa-raygun', 'fa-suitcase-medical',
  'fa-syringe', 'fa-tablets', 'fa-teeth', 'fa-teeth-open', 'fa-thermometer',
  'fa-tooth', 'fa-user-doctor', 'fa-user-injured', 'fa-user-nurse',
  'fa-vial', 'fa-vial-circle-check', 'fa-vial-virus', 'fa-vials',
  'fa-virus', 'fa-virus-slash', 'fa-weight-scale', 'fa-wheelchair',

  // Money + Finance
  'fa-austral-sign', 'fa-baht-sign', 'fa-bitcoin-sign', 'fa-brazilian-real-sign',
  'fa-cash-register', 'fa-cedi-sign', 'fa-cent-sign', 'fa-chart-line',
  'fa-chart-pie', 'fa-coins', 'fa-colon-sign', 'fa-credit-card',
  'fa-cruzeiro-sign', 'fa-dollar-sign', 'fa-dong-sign', 'fa-euro-sign',
  'fa-florin-sign', 'fa-franc-sign', 'fa-guarani-sign', 'fa-hryvnia-sign',
  'fa-indian-rupee-sign', 'fa-kip-sign', 'fa-lari-sign', 'fa-litecoin-sign',
  'fa-manat-sign', 'fa-mill-sign', 'fa-money-bill', 'fa-money-bill-1',
  'fa-money-bill-1-wave', 'fa-money-bill-transfer', 'fa-money-bill-trend-up',
  'fa-money-bill-wave', 'fa-money-bill-wheat', 'fa-money-bills',
  'fa-naira-sign', 'fa-naira-sign', 'fa-peso-sign', 'fa-poll',
  'fa-pound-sign', 'fa-ruble-sign', 'fa-rupee-sign', 'fa-rupiah-sign',
  'fa-sack-dollar', 'fa-sack-xmark', 'fa-shear-sign',
  'fa-sterling-sign', 'fa-tenge-sign', 'fa-tenge-sign', 'fa-turkish-lira-sign',
  'fa-vault', 'fa-wallet', 'fa-won-sign', 'fa-yen-sign',

  // Nature
  'fa-binoculars', 'fa-bugs', 'fa-burst', 'fa-campfire',
  'fa-cloud-bolt', 'fa-cloud-meatball', 'fa-cloud-moon', 'fa-cloud-rain',
  'fa-cloud-showers-heavy', 'fa-cloud-showers-water', 'fa-cloud-sun',
  'fa-cloudscale', 'fa-cloudsmith', 'fa-cloudversify', 'fa-crow',
  'fa-dove', 'fa-dragon', 'fa-feather', 'fa-feather-pointed', 'fa-fire',
  'fa-fire-flame-curved', 'fa-fire-flame-simple', 'fa-fish', 'fa-frog',
  'fa-globe', 'fa-hill-avalanche', 'fa-hill-rockslide', 'fa-icicles',
  'fa-leaf', 'fa-location-dot', 'fa-meteor', 'fa-moon', 'fa-mountain',
  'fa-mountain-city', 'fa-mountain-sun', 'fa-paw', 'fa-plant-wilt',
  'fa-raindrops', 'fa-seedling', 'fa-shoe-prints', 'fa-shrub',
  'fa-snowflake', 'fa-snowman', 'fa-snowplow', 'fa-spa', 'fa-spider',
  'fa-sprout', 'fa-sun', 'fa-sun-plant-wilt', 'fa-temperature-arrow-down',
  'fa-temperature-arrow-up', 'fa-temperature-empty', 'fa-temperature-full',
  'fa-temperature-half', 'fa-temperature-high', 'fa-temperature-low',
  'fa-temperature-quarter', 'fa-temperature-three-quarters',
  'fa-tornado', 'fa-tree', 'fa-tree-city', 'fa-volcano', 'fa-water',
  'fa-wave', 'fa-wind', 'fa-worm',

  // Objects
  'fa-bell', 'fa-book', 'fa-bookmark', 'fa-box', 'fa-box-archive',
  'fa-box-open', 'fa-boxes-stacked', 'fa-briefcase', 'fa-bullhorn',
  'fa-cake-candles', 'fa-cart-shopping', 'fa-coins', 'fa-compact-disc',
  'fa-compass', 'fa-cube', 'fa-cubes', 'fa-dice', 'fa-dice-five',
  'fa-dice-four', 'fa-dice-one', 'fa-dice-six', 'fa-dice-three',
  'fa-dice-two', 'fa-dolly', 'fa-dong-sign', 'fa-door-closed',
  'fa-door-open', 'fa-drum', 'fa-drum-steelpan', 'fa-envelope',
  'fa-envelope-open', 'fa-eraser', 'fa-fan', 'fa-feather',
  'fa-fingerprint', 'fa-fire-burner', 'fa-fire-extinguisher', 'fa-flag',
  'fa-flag-checkered', 'fa-flask', 'fa-floppy-disk', 'fa-futbol',
  'fa-gamepad', 'fa-gas-pump', 'fa-gavel', 'fa-gem', 'fa-gift',
  'fa-gifts', 'fa-glass-water', 'fa-globe', 'fa-graduation-cap',
  'fa-guitar', 'fa-hat-cowboy', 'fa-hat-wizard', 'fa-headphones',
  'fa-headset', 'fa-helmet-safety', 'fa-helmet-un', 'fa-highlighter',
  'fa-igloo', 'fa-jar', 'fa-key', 'fa-keyboard', 'fa-kitchen-set',
  'fa-lamp', 'fa-life-ring', 'fa-lightbulb', 'fa-link', 'fa-lock',
  'fa-lock-open', 'fa-magnet', 'fa-magnifying-glass', 'fa-map',
  'fa-map-location', 'fa-map-location-dot', 'fa-map-pin',
  'fa-martini-glass', 'fa-martini-glass-citrus', 'fa-medal',
  'fa-microchip', 'fa-mobile', 'fa-mobile-button', 'fa-mobile-retro',
  'fa-mobile-screen', 'fa-mobile-screen-button', 'fa-money-bill',
  'fa-money-bill-1', 'fa-money-bill-1-wave', 'fa-money-bill-wave',
  'fa-mug-hot', 'fa-mug-saucer', 'fa-music', 'fa-newspaper',
  'fa-nfc-magnifying-glass', 'fa-notdef', 'fa-note-sticky',
  'fa-object-group', 'fa-object-ungroup', 'fa-outdent', 'fa-pager',
  'fa-paint-roller', 'fa-paintbrush', 'fa-paper-plane', 'fa-paperclip',
  'fa-pause', 'fa-paw', 'fa-pen', 'fa-pen-clip', 'fa-pen-fancy',
  'fa-pen-nib', 'fa-pen-ruler', 'fa-pen-to-square', 'fa-pencil',
  'fa-people-carry-box', 'fa-people-group', 'fa-percent',
  'fa-person', 'fa-phone', 'fa-phone-flip', 'fa-phone-slash',
  'fa-phone-volume', 'fa-photo-film', 'fa-piggy-bank', 'fa-plane',
  'fa-play', 'fa-plug', 'fa-plus', 'fa-podcast', 'fa-poo', 'fa-poop',
  'fa-power-off', 'fa-prescription', 'fa-print', 'fa-puzzle-piece',
  'fa-qrcode', 'fa-quote-left', 'fa-quote-right', 'fa-rectangle-list',
  'fa-rectangle-xmark', 'fa-recycle', 'fa-registered', 'fa-repeat',
  'fa-reply', 'fa-reply-all', 'fa-retweet', 'fa-ribbon', 'fa-ring',
  'fa-road', 'fa-rocket', 'fa-route', 'fa-rss', 'fa-ruler',
  'fa-ruler-combined', 'fa-ruler-horizontal', 'fa-ruler-vertical',
  'fa-sack-dollar', 'fa-save', 'fa-scale-balanced', 'fa-scale-unbalanced',
  'fa-scale-unbalanced-flip', 'fa-school', 'fa-scissors',
  'fa-screwdriver', 'fa-screwdriver-wrench', 'fa-scroll', 'fa-sd-card',
  'fa-shapes', 'fa-share', 'fa-share-from-square', 'fa-shield',
  'fa-shield-halved', 'fa-shirt', 'fa-shop', 'fa-shower',
  'fa-shrimp', 'fa-signal', 'fa-signature', 'fa-sitemap', 'fa-skiing',
  'fa-skull', 'fa-sliders', 'fa-snowboarding', 'fa-snowflake',
  'fa-snowman', 'fa-socks', 'fa-solar-panel', 'fa-sort', 'fa-sort-down',
  'fa-sort-up', 'fa-spa', 'fa-spoon', 'fa-square-arrow-up-right',
  'fa-square-caret-down', 'fa-square-caret-left', 'fa-square-caret-right',
  'fa-square-caret-up', 'fa-square-envelope', 'fa-square-full',
  'fa-square-h', 'fa-square-minus', 'fa-square-parking', 'fa-square-pen',
  'fa-square-phone', 'fa-square-phone-flip', 'fa-square-poll-horizontal',
  'fa-square-poll-vertical', 'fa-square-root-variable', 'fa-square-rss',
  'fa-square-share-nodes', 'fa-square-up-right', 'fa-square-xmark',
  'fa-stamp', 'fa-star', 'fa-star-half', 'fa-stapler',
  'fa-stopwatch', 'fa-store', 'fa-stretchmark', 'fa-suitcase',
  'fa-suitcase-medical', 'fa-suitcase-rolling', 'fa-sun', 'fa-sunglasses',
  'fa-table', 'fa-table-columns', 'fa-table-list', 'fa-table-tennis',
  'fa-tag', 'fa-tags', 'fa-tape', 'fa-taxi', 'fa-teeth', 'fa-teeth-open',
  'fa-television', 'fa-tennis-ball', 'fa-terminal', 'fa-text-height',
  'fa-text-slash', 'fa-text-width', 'fa-thermometer', 'fa-thumbs-down',
  'fa-thumbs-up', 'fa-thumbtack', 'fa-ticket', 'fa-ticket-simple',
  'fa-timeline', 'fa-toggle-off', 'fa-toggle-on', 'fa-toilet',
  'fa-toilet-paper', 'fa-toolbox', 'fa-tools', 'fa-tooth',
  'fa-torii-gate', 'fa-tornado', 'fa-tower-broadcast', 'fa-tower-cell',
  'fa-tower-observation', 'fa-trademark', 'fa-traffic-light',
  'fa-trailer', 'fa-train', 'fa-train-subway', 'fa-train-tram',
  'fa-trash', 'fa-trash-arrow-up', 'fa-trash-can', 'fa-trash-can-arrow-up',
  'fa-tree', 'fa-tree-city', 'fa-triangle-exclamation', 'fa-trophy',
  'fa-truck', 'fa-truck-arrow-right', 'fa-truck-droplet', 'fa-truck-fast',
  'fa-truck-field', 'fa-truck-field-un', 'fa-truck-front',
  'fa-truck-medical', 'fa-truck-monster', 'fa-truck-pickup', 'fa-truck-plane',
  'fa-tv', 'fa-umbrella', 'fa-umbrella-beach', 'fa-underline',
  'fa-undo', 'fa-universal-access', 'fa-unlock', 'fa-unlock-keyhole',
  'fa-upload', 'fa-up-right-and-down-left-from-center', 'fa-up-right-from-square',
  'fa-user', 'fa-utensils', 'fa-van-shuttle', 'fa-vault', 'fa-vector-square',
  'fa-venus', 'fa-venus-double', 'fa-venus-mars', 'fa-video',
  'fa-video-slash', 'fa-voicemail', 'fa-volleyball', 'fa-volume-high',
  'fa-volume-low', 'fa-volume-off', 'fa-volume-xmark', 'fa-walkie-talkie',
  'fa-wallet', 'fa-wand-magic', 'fa-wand-magic-sparkles', 'fa-wand-sparkles',
  'fa-warehouse', 'fa-water', 'fa-water-ladder', 'fa-wave-square',
  'fa-weight-hanging', 'fa-weight-scale', 'fa-wheelchair',
  'fa-wheelchair-move', 'fa-whiskey-glass', 'fa-wifi', 'fa-wind',
  'fa-window-maximize', 'fa-window-minimize', 'fa-window-restore',
  'fa-wine-bottle', 'fa-wine-glass', 'fa-wine-glass-empty',
  'fa-won-sign', 'fa-wrench', 'fa-xmark', 'fa-xmarks-lines',
  'fa-yen-sign', 'fa-yin-yang',

  // Payments + Commerce (curated subset)
  'fa-bell', 'fa-bell-concierge', 'fa-bell-slash', 'fa-bookmark',
  'fa-briefcase', 'fa-building', 'fa-bullhorn', 'fa-calculator',
  'fa-calendar', 'fa-cart-arrow-down', 'fa-cart-plus', 'fa-cart-shopping',
  'fa-cash-register', 'fa-chart-line', 'fa-check', 'fa-check-double',
  'fa-circle', 'fa-circle-check', 'fa-circle-dollar-to-slot',
  'fa-circle-info', 'fa-circle-xmark', 'fa-coins', 'fa-copy',
  'fa-credit-card', 'fa-crown', 'fa-dollar-sign', 'fa-door-closed',
  'fa-door-open', 'fa-envelope', 'fa-envelope-open', 'fa-eye',
  'fa-eye-slash', 'fa-filter', 'fa-flag', 'fa-gift', 'fa-gifts',
  'fa-globe', 'fa-hand-holding-dollar', 'fa-handshake', 'fa-headset',
  'fa-heart', 'fa-home', 'fa-house', 'fa-id-card', 'fa-image',
  'fa-images', 'fa-key', 'fa-life-ring', 'fa-lightbulb', 'fa-link',
  'fa-list', 'fa-list-check', 'fa-location-dot', 'fa-lock',
  'fa-lock-open', 'fa-map-marker', 'fa-message', 'fa-money-bill',
  'fa-money-bill-wave', 'fa-newspaper', 'fa-paper-plane', 'fa-pen',
  'fa-percent', 'fa-phone', 'fa-phone-volume', 'fa-piggy-bank',
  'fa-qrcode', 'fa-question', 'fa-receipt', 'fa-rectangle-list',
  'fa-search', 'fa-share', 'fa-shield', 'fa-shop', 'fa-sitemap',
  'fa-sliders', 'fa-sms', 'fa-star', 'fa-store', 'fa-tag', 'fa-tags',
  'fa-thumbs-down', 'fa-thumbs-up', 'fa-ticket', 'fa-ticket-simple',
  'fa-truck', 'fa-truck-fast', 'fa-truck-ramp-box', 'fa-unlock',
  'fa-user', 'fa-user-check', 'fa-user-clock', 'fa-user-gear',
  'fa-user-pen', 'fa-user-plus', 'fa-user-shield', 'fa-user-tag',
  'fa-user-tie', 'fa-users', 'fa-users-gear', 'fa-users-slash',
  'fa-vault', 'fa-wallet', 'fa-warehouse', 'fa-xmark',

  // Science + Tech
  'fa-atom', 'fa-bolt', 'fa-brain', 'fa-cube', 'fa-cubes', 'fa-diagram-project',
  'fa-dna', 'fa-flask', 'fa-flask-vial', 'fa-frog', 'fa-magnet',
  'fa-microscope', 'fa-mortar-pestle', 'fa-pills', 'fa-prescription-bottle',
  'fa-radiation', 'fa-seedling', 'fa-syringe', 'fa-tablets', 'fa-vial',
  'fa-vial-circle-check', 'fa-vial-virus', 'fa-vials',
];

/**
 * Quick-pick grid for the most common add-on icons (16 entries). User
 * can click to select without typing. The full FA 6 free-solid set
 * (~580 entries above) is also exposed via the datalist autocomplete.
 */
export const POPULAR_FA_ICONS: readonly string[] = [
  'fa-bullhorn',
  'fa-robot',
  'fa-cogs',
  'fa-file-invoice',
  'fa-file-alt',
  'fa-ticket-alt',
  'fa-mobile-alt',
  'fa-box',
  'fa-tools',
  'fa-project-diagram',
  'fa-puzzle-piece',
  'fa-rocket',
  'fa-shield-alt',
  'fa-chart-line',
  'fa-tachometer-alt',
  'fa-headset',
];