-- ============================================================
-- Rafter SECDEF REVOKE Migration
-- Generated: 2026-06-21
-- Total REVOKE statements: 286
-- DO NOT APPLY WITHOUT MANUAL REVIEW
-- ============================================================

-- ============================================================
-- REVOKE FROM authenticated (69 functions)
-- ============================================================
REVOKE EXECUTE ON FUNCTION public.activate_recurring_service_on_payment() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.auto_assign_client_creator() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.auto_create_availability_schedules_for_company() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.check_retention_before_delete() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.fn_auto_assign_client_on_booking_change() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.fn_auto_assign_service_on_booking_change() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.fn_auto_quote_on_client_assigned() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.fn_cancel_quote_on_booking_cancel() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.fn_sync_booking_quote_id() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gdpr_audit_booking_clinical_notes_changes() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gdpr_audit_booking_documents_changes() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gdpr_audit_clients_changes() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gdpr_audit_clinical_notes_changes() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gdpr_audit_consent_changes() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gdpr_audit_invoices_changes() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gdpr_breach_created_notify() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.handle_comment_notifications() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.handle_gdpr_consent_notification() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.handle_global_audit() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.handle_new_auth_user_link() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.handle_new_client_link() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.handle_new_project_comment() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.handle_new_user_link() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.handle_new_user_registration() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.handle_project_auto_move() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.handle_ticket_assignment_notification() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.handle_ticket_audit_log() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.handle_ticket_auto_assignment() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.handle_ticket_comment_automation() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.handle_ticket_comment_notification() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.handle_ticket_critical_notification() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.handle_ticket_first_response() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.handle_ticket_notifications() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.handle_ticket_soft_delete() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.handle_ticket_state_transition() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.handle_updated_at() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.handle_verifactu_voiding() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.is_super_admin_by_id(p_user_id uuid) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.log_booking_changes() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.maintain_ticket_opened_status() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.notify_booking_notifier() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.notify_holded_booking_confirmed() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.notify_holded_booking_estimate() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.notify_on_recurring_budget_created() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.notify_on_service_contract() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.notify_owner_on_gdpr_request() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.notify_push_on_notification_insert() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.notify_session_created() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.seed_gdpr_processing_activities() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.set_initial_ticket_stage() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.set_ticket_number() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.sync_gdpr_to_client_consent() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.trg_auto_create_quote_on_booking() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.trg_delete_booking_rejects_quote() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.trg_fn_bookings_notify_change() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.trg_generate_quote_on_booking_update() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.trg_mail_account_create_folders() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.trg_mark_quote_invoiced_on_invoice_insert() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.trg_session_close_to_invoice() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.trg_sync_booking_to_invoice_payment() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.trg_sync_client_consent_cache() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.trg_sync_invoice_to_booking_payment() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.trigger_audit_access_requests() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.trigger_audit_consent_records() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.trigger_encrypt_booking_form_responses() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.trigger_validate_booking_consent() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.update_client_stats_on_change() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.update_mail_folder_unread_count() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.validate_project_association() FROM authenticated;

-- ============================================================
-- REVOKE FROM anon (217 functions)
-- ============================================================
REVOKE EXECUTE ON FUNCTION public.activate_recurring_service_on_payment() FROM anon;
REVOKE EXECUTE ON FUNCTION public.auto_assign_client(p_client_id uuid, p_professional_id uuid, p_company_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.auto_assign_client_creator() FROM anon;
REVOKE EXECUTE ON FUNCTION public.auto_create_availability_schedules_for_company() FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_retention_before_delete() FROM anon;
REVOKE EXECUTE ON FUNCTION public.create_booking_clinical_note(p_booking_id uuid, p_content text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.create_mail_folder_rpc(p_account_id uuid, p_name character varying, p_parent_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.enqueue_aws_job(p_job_type text, p_company_id uuid, p_domain text, p_payload jsonb, p_run_at timestamp with time zone, p_max_attempts integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.ensure_inbound_config(p_company_id uuid, p_domain text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.fn_auto_assign_client_on_booking_change() FROM anon;
REVOKE EXECUTE ON FUNCTION public.fn_auto_assign_service_on_booking_change() FROM anon;
REVOKE EXECUTE ON FUNCTION public.fn_auto_quote_on_client_assigned() FROM anon;
REVOKE EXECUTE ON FUNCTION public.fn_cancel_quote_on_booking_cancel() FROM anon;
REVOKE EXECUTE ON FUNCTION public.fn_sync_booking_quote_id() FROM anon;
REVOKE EXECUTE ON FUNCTION public.gdpr_audit_booking_clinical_notes_changes() FROM anon;
REVOKE EXECUTE ON FUNCTION public.gdpr_audit_booking_documents_changes() FROM anon;
REVOKE EXECUTE ON FUNCTION public.gdpr_audit_clients_changes() FROM anon;
REVOKE EXECUTE ON FUNCTION public.gdpr_audit_clinical_notes_changes() FROM anon;
REVOKE EXECUTE ON FUNCTION public.gdpr_audit_consent_changes() FROM anon;
REVOKE EXECUTE ON FUNCTION public.gdpr_audit_invoices_changes() FROM anon;
REVOKE EXECUTE ON FUNCTION public.gdpr_breach_created_notify() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_public_blocked_dates(p_company_id uuid, p_professional_id uuid, p_from date, p_to date) FROM anon;
REVOKE EXECUTE ON FUNCTION public.handle_comment_notifications() FROM anon;
REVOKE EXECUTE ON FUNCTION public.handle_gdpr_consent_notification() FROM anon;
REVOKE EXECUTE ON FUNCTION public.handle_global_audit() FROM anon;
REVOKE EXECUTE ON FUNCTION public.handle_new_auth_user_link() FROM anon;
REVOKE EXECUTE ON FUNCTION public.handle_new_client_link() FROM anon;
REVOKE EXECUTE ON FUNCTION public.handle_new_project_comment() FROM anon;
REVOKE EXECUTE ON FUNCTION public.handle_new_user_link() FROM anon;
REVOKE EXECUTE ON FUNCTION public.handle_new_user_registration() FROM anon;
REVOKE EXECUTE ON FUNCTION public.handle_project_auto_move() FROM anon;
REVOKE EXECUTE ON FUNCTION public.handle_ticket_assignment_notification() FROM anon;
REVOKE EXECUTE ON FUNCTION public.handle_ticket_audit_log() FROM anon;
REVOKE EXECUTE ON FUNCTION public.handle_ticket_auto_assignment() FROM anon;
REVOKE EXECUTE ON FUNCTION public.handle_ticket_comment_automation() FROM anon;
REVOKE EXECUTE ON FUNCTION public.handle_ticket_comment_notification() FROM anon;
REVOKE EXECUTE ON FUNCTION public.handle_ticket_critical_notification() FROM anon;
REVOKE EXECUTE ON FUNCTION public.handle_ticket_first_response() FROM anon;
REVOKE EXECUTE ON FUNCTION public.handle_ticket_notifications() FROM anon;
REVOKE EXECUTE ON FUNCTION public.handle_ticket_soft_delete() FROM anon;
REVOKE EXECUTE ON FUNCTION public.handle_ticket_state_transition() FROM anon;
REVOKE EXECUTE ON FUNCTION public.handle_updated_at() FROM anon;
REVOKE EXECUTE ON FUNCTION public.handle_verifactu_voiding() FROM anon;
REVOKE EXECUTE ON FUNCTION public.insert_or_get_address(p_direccion text, p_locality_id uuid, p_numero text, p_usuario_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.is_super_admin_by_id(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.log_booking_changes() FROM anon;
REVOKE EXECUTE ON FUNCTION public.maintain_ticket_opened_status() FROM anon;
REVOKE EXECUTE ON FUNCTION public.move_mail_messages(p_message_ids uuid[], p_target_folder_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.notify_booking_notifier() FROM anon;
REVOKE EXECUTE ON FUNCTION public.notify_holded_booking_confirmed() FROM anon;
REVOKE EXECUTE ON FUNCTION public.notify_holded_booking_estimate() FROM anon;
REVOKE EXECUTE ON FUNCTION public.notify_on_recurring_budget_created() FROM anon;
REVOKE EXECUTE ON FUNCTION public.notify_on_service_contract() FROM anon;
REVOKE EXECUTE ON FUNCTION public.notify_owner_on_gdpr_request() FROM anon;
REVOKE EXECUTE ON FUNCTION public.notify_push_on_notification_insert() FROM anon;
REVOKE EXECUTE ON FUNCTION public.notify_session_created() FROM anon;
REVOKE EXECUTE ON FUNCTION public.rename_mail_folder_rpc(p_folder_id uuid, p_new_name character varying) FROM anon;
REVOKE EXECUTE ON FUNCTION public.seed_company_filter_visibility(p_company_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.seed_gdpr_processing_activities() FROM anon;
REVOKE EXECUTE ON FUNCTION public.set_initial_ticket_stage() FROM anon;
REVOKE EXECUTE ON FUNCTION public.set_ticket_number() FROM anon;
REVOKE EXECUTE ON FUNCTION public.suggest_folders_rpc(p_account_id uuid, p_sender_email text, p_subject text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.sync_gdpr_to_client_consent() FROM anon;
REVOKE EXECUTE ON FUNCTION public.toggle_smart_folders_rpc(p_account_id uuid, p_enabled boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.trg_auto_create_quote_on_booking() FROM anon;
REVOKE EXECUTE ON FUNCTION public.trg_delete_booking_rejects_quote() FROM anon;
REVOKE EXECUTE ON FUNCTION public.trg_fn_bookings_notify_change() FROM anon;
REVOKE EXECUTE ON FUNCTION public.trg_generate_quote_on_booking_update() FROM anon;
REVOKE EXECUTE ON FUNCTION public.trg_mail_account_create_folders() FROM anon;
REVOKE EXECUTE ON FUNCTION public.trg_mark_quote_invoiced_on_invoice_insert() FROM anon;
REVOKE EXECUTE ON FUNCTION public.trg_session_close_to_invoice() FROM anon;
REVOKE EXECUTE ON FUNCTION public.trg_sync_booking_to_invoice_payment() FROM anon;
REVOKE EXECUTE ON FUNCTION public.trg_sync_client_consent_cache() FROM anon;
REVOKE EXECUTE ON FUNCTION public.trg_sync_invoice_to_booking_payment() FROM anon;
REVOKE EXECUTE ON FUNCTION public.trigger_audit_access_requests() FROM anon;
REVOKE EXECUTE ON FUNCTION public.trigger_audit_consent_records() FROM anon;
REVOKE EXECUTE ON FUNCTION public.trigger_encrypt_booking_form_responses() FROM anon;
REVOKE EXECUTE ON FUNCTION public.trigger_validate_booking_consent() FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_client_stats_on_change() FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_mail_folder_unread_count() FROM anon;
REVOKE EXECUTE ON FUNCTION public.validate_project_association() FROM anon;
REVOKE EXECUTE ON FUNCTION public._test_gotrue_flow() FROM anon;
REVOKE EXECUTE ON FUNCTION public.accept_company_invitation_admin(p_invitation_token text, p_auth_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.activate_invited_user(auth_user_id uuid, user_email text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.add_client_note(p_client_id uuid, p_company_id uuid, p_content text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_assign_company_plan(p_company_id uuid, p_plan_id text, p_notes text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_create_program(p_name text, p_description text, p_price numeric, p_class_type_id integer, p_class_slots jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_list_company_modules(p_company_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_toggle_company_module(p_company_id uuid, p_module_key text, p_status text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.auth_user_id_from_token() FROM anon;
REVOKE EXECUTE ON FUNCTION public.cancel_marketing_send(p_campaign_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.change_company_plan(p_company_id uuid, p_plan_id text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_gdpr_compliance() FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_public_company_module(p_company_id uuid, p_module_key text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.classify_incoming_email_rpc(p_message_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.clean_expired_pending_users() FROM anon;
REVOKE EXECUTE ON FUNCTION public.cleanup_current_duplicates() FROM anon;
REVOKE EXECUTE ON FUNCTION public.cleanup_duplicate_companies() FROM anon;
REVOKE EXECUTE ON FUNCTION public.cleanup_expired_gdpr_data() FROM anon;
REVOKE EXECUTE ON FUNCTION public.cleanup_pending_user() FROM anon;
REVOKE EXECUTE ON FUNCTION public.client_cancel_booking(p_booking_id uuid, p_reason text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.client_create_booking(p_company_id uuid, p_service_id uuid, p_start_time timestamp with time zone, p_end_time timestamp with time zone) FROM anon;
REVOKE EXECUTE ON FUNCTION public.client_dedup_rollback() FROM anon;
REVOKE EXECUTE ON FUNCTION public.client_get_preferences() FROM anon;
REVOKE EXECUTE ON FUNCTION public.client_reschedule_booking(p_booking_id uuid, p_new_start_time timestamp with time zone, p_new_end_time timestamp with time zone) FROM anon;
REVOKE EXECUTE ON FUNCTION public.client_update_preferences(p_email_notifications boolean, p_sms_notifications boolean, p_marketing_accepted boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.client_update_profile(p_full_name text, p_phone text, p_avatar_url text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.convert_quote_to_invoice(p_quote_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.convert_quote_to_invoice(p_quote_id uuid, p_invoice_series_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.count_customers_by_user(target_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.count_marketing_audience(p_campaign_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.count_unassigned_clients(p_company_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.create_address_dev(target_user_id uuid, p_direccion character varying, p_numero character varying, p_piso character varying, p_puerta character varying, p_codigo_postal character varying, p_locality_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.create_address_rpc(p_direccion text, p_locality_id uuid, p_numero text, p_piso text, p_puerta text, p_bloque text, p_escalera text, p_cod_postal text, p_provincia text, p_pais text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.create_attachment(p_company_id uuid, p_job_id uuid, p_file_name text, p_file_size integer, p_mime_type text, p_subfolder text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.create_booking_with_validations(p_user_id integer, p_class_session_id integer, p_booking_date_time timestamp with time zone) FROM anon;
REVOKE EXECUTE ON FUNCTION public.create_default_project_stages(company_uuid uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.create_gdpr_access_request(p_subject_email text, p_request_type text, p_subject_name text, p_request_details jsonb, p_requesting_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.create_locality_rpc(p_name text, p_postal_code text, p_province text, p_country text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.cron_scan_incomplete_bookings() FROM anon;
REVOKE EXECUTE ON FUNCTION public.debug_admin_access() FROM anon;
REVOKE EXECUTE ON FUNCTION public.debug_auth_status() FROM anon;
REVOKE EXECUTE ON FUNCTION public.delete_stage_safe_rpc(p_stage_id uuid, p_reassign_to uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.detect_overdue_arco_requests() FROM anon;
REVOKE EXECUTE ON FUNCTION public.ensure_mail_system_folders(p_account_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.f_analytics_occupancy_heatmap(p_company_id uuid, p_start_date timestamp with time zone, p_end_date timestamp with time zone) FROM anon;
REVOKE EXECUTE ON FUNCTION public.f_analytics_revenue_forecast(p_company_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.f_analytics_top_performers(p_company_id uuid, p_month_date date) FROM anon;
REVOKE EXECUTE ON FUNCTION public.f_analytics_top_services(p_start date, p_end date, p_limit integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.f_booking_analytics_monthly(p_start date, p_end date) FROM anon;
REVOKE EXECUTE ON FUNCTION public.f_invoice_collection_status(p_start date, p_end date) FROM anon;
REVOKE EXECUTE ON FUNCTION public.f_invoice_kpis_monthly_debug(p_start date, p_end date) FROM anon;
REVOKE EXECUTE ON FUNCTION public.f_invoice_kpis_monthly_temp(p_start date, p_end date) FROM anon;
REVOKE EXECUTE ON FUNCTION public.f_mail_get_thread_messages(p_thread_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.f_mail_get_threads(p_account_id uuid, p_folder_name text, p_limit integer, p_offset integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.f_marketing_get_audience(p_company_id uuid, p_criteria jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.f_marketing_get_automation_audience(p_company_id uuid, p_trigger_type campaign_trigger_type, p_config jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.f_quote_cube(p_start date, p_end date) FROM anon;
REVOKE EXECUTE ON FUNCTION public.f_quote_kpis_monthly_enhanced(p_start date, p_end date) FROM anon;
REVOKE EXECUTE ON FUNCTION public.f_quote_top_items_monthly(p_start date, p_end date, p_limit integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.f_refresh_analytics_views() FROM anon;
REVOKE EXECUTE ON FUNCTION public.finalize_marketing_campaign(p_campaign_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.find_client_by_phone_last9(p_company_id uuid, p_phone_last9 text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.fix_bet_drop_link() FROM anon;
REVOKE EXECUTE ON FUNCTION public.fn_auto_assign_client_on_booking_insert() FROM anon;
REVOKE EXECUTE ON FUNCTION public.fn_is_variant_visible(p_variant_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gdpr_accept_consent(p_token text, p_preferences jsonb, p_evidence jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gdpr_decline_consent(p_token text, p_evidence jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gdpr_detect_anomalies() FROM anon;
REVOKE EXECUTE ON FUNCTION public.gdpr_enforce_retention() FROM anon;
REVOKE EXECUTE ON FUNCTION public.gdpr_export_processing_registry(p_company_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gdpr_get_consent_request(p_token text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gdpr_verify_backup_status() FROM anon;
REVOKE EXECUTE ON FUNCTION public.generate_verifactu_hash(p_invoice_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_addresses_dev(target_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_all_companies_stats() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_all_users_with_customers() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_auth_company_id() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_availability_data(p_company_id uuid, p_start_date timestamp with time zone, p_end_date timestamp with time zone) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_booking_config(p_company_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_client_consent_request(p_token uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_client_consent_status(p_client_id uuid, p_requesting_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_client_notes(p_client_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_clients_to_inactivate(inactivity_days integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_company_address(p_company_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_company_contact_email(p_company_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_company_display_name(p_company_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_company_dpo_info(p_company_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_company_services_with_variants(p_company_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_current_company_plan(p_company_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_daily_revenue(start_date timestamp with time zone, end_date timestamp with time zone, p_company_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_job_attachments(p_job_id uuid, p_company_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_marketing_audience(p_campaign_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_my_client_ids() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_my_service_variant_company_ids() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_pending_breach_notifications(p_company_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_pending_invitation_by_email(p_email text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_provider_tokens(provider_name text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_revenue_by_professional(start_date timestamp with time zone, end_date timestamp with time zone, p_company_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_revenue_by_service(start_date timestamp with time zone, end_date timestamp with time zone, p_company_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_service_with_variants(p_service_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_sessions_with_booking_counts(p_start_date date, p_end_date date) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_user_jwt_claims(p_auth_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_user_role() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_visible_service_ids() FROM anon;
REVOKE EXECUTE ON FUNCTION public.handle_company_registration(p_auth_user_id uuid, p_email text, p_full_name text, p_company_name text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.has_valid_dpa(p_company_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.invite_user_to_company_debug(user_email text, user_name text, user_role text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.invoke_process_recurring_quotes() FROM anon;
REVOKE EXECUTE ON FUNCTION public.is_company_admin_or_supervisor(company_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.is_stage_hidden_for_company(p_stage_id uuid, p_company_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.join_waiting_list_v2(p_user_id bigint, p_class_session_id bigint, p_user_package_id bigint) FROM anon;
REVOKE EXECUTE ON FUNCTION public.join_waiting_list_v2(p_user_id integer, p_class_session_id bigint, p_user_package_id bigint) FROM anon;
REVOKE EXECUTE ON FUNCTION public.link_ticket_device(p_ticket_id uuid, p_device_id uuid, p_relation_type text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.list_company_devices(p_company_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.log_audit_event(p_company_id uuid, p_action text, p_entity_type text, p_entity_id uuid, p_metadata jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.log_gdpr_audit(p_action_type text, p_table_name text, p_record_id uuid, p_subject_email text, p_purpose text, p_old_values jsonb, p_new_values jsonb, p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.log_marketing_send(p_campaign_id uuid, p_subject_email text, p_status text, p_error text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.log_security_event(p_event_type text, p_event_detail text, p_success boolean, p_user_id uuid, p_ip_address text, p_user_agent text, p_function_name text, p_details jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.mark_client_accessed(p_client_id uuid, p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.notify_owner_email_request(p_company_id uuid, p_user_id uuid, p_user_name text, p_user_email text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.process_gdpr_deletion_request(p_request_id uuid, p_approve boolean, p_rejection_reason text, p_processing_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.process_inactive_clients() FROM anon;
REVOKE EXECUTE ON PROCEDURE public.refresh_analytics_materialized_views() FROM anon;
REVOKE EXECUTE ON PROCEDURE public.refresh_quotes_materialized_views() FROM anon;
REVOKE EXECUTE ON FUNCTION public.register_new_owner_from_invite(p_invitation_token text, p_company_name text, p_company_nif text, p_user_name text, p_user_surname text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.remove_or_deactivate_client_rpc(p_client_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.reorder_stages(stage_ids uuid[]) FROM anon;
REVOKE EXECUTE ON FUNCTION public.rls_auto_enable() FROM anon;
REVOKE EXECUTE ON FUNCTION public.seed_booking_source_icons_for_company(p_company_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.storage_get_company_id() FROM anon;
REVOKE EXECUTE ON FUNCTION public.sync_client_profile() FROM anon;
REVOKE EXECUTE ON FUNCTION public.trigger_update_last_accessed() FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_client_consent(p_client_id uuid, p_consent_type text, p_consent_given boolean, p_consent_method text, p_consent_evidence jsonb, p_updating_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.upsert_client_rpc(p_first_name text, p_last_name text, p_email text, p_phone text, p_address text, p_city text, p_fiscal_id text, p_client_id uuid, p_metadata jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.upsert_verifactu_settings(p_company_id uuid, p_software_code text, p_software_name text, p_software_version text, p_issuer_nif text, p_environment text, p_is_active boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.upsert_verifactu_settings(psoftware_code text, pissuer_nif text, pcert_pem text, pkey_pem text, pkey_passphrase text, penvironment text) FROM anon;
